name: Update every 59 min
on:
  schedule:
    - cron: '59 * * * *'
jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: install python and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run notebooks
        id: run_notebooks
        run: |
          jupyter nbconvert --to notebook --inplace --execute scripts/Random_Fig_Daily.ipynb
      - name: git status
        id: git-status
        run: |
          git config --global user.email "Random_Fig_Daily-bot@example.com"
          git config --global user.name "Random_Fig_Daily-bot"
          echo ::set-output name=result::$(git status ./ | tr -d "\n" | grep -c "nothing to commit")
      - name: commit
        if: steps.git-status.outputs.result == 0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DATE: ${{ steps.update-script.outputs.result }}
        run: |
          git add -A
          git commit -m "[ci] $(date +%H)"
          git push -q "https://$GH_TOKEN@github.com/dquintani/GreenhouseData.git" main
